version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - taskiq-worker
      - taskiq-scheduler
    networks:
      - cartolapy

  taskiq-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: taskiq worker backend.tkq:broker
    depends_on:
      - backend
    networks:
      - cartolapy

  taskiq-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    command: taskiq scheduler backend.tkq_sched:scheduler
    depends_on:
      - backend
    networks:
      - cartolapy

networks:
  cartolapy:
    driver: bridge
